#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "sftpgo"
name = "sftpgo"
description.en = "Fully featured and highly configurable SFTP server"
description.fr = "Serveur SFTP complet et hautement configurable"

version = "2.6.6~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://sftpgo.com/"
admindoc = "https://yunohost.org/packaging_apps"
code = "https://github.com/drakkan/sftpgo"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/drakkan/sftpgo/releases/download/v2.6.6/sftpgo_v2.6.6_linux_x86_64.tar.xz"
    sha256 = "1fd5411d973efddc4058b725141c08385e2556ed4239131a38d535bf9a6c82ff"

    # autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
