#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

tempdir="$(mktemp -d)"

ynh_setup_source --dest_dir="$install_dir"

# extract the binary from the deb file
dpkg-deb -R "$install_dir/sftpgo.deb" "$tempdir"

mv "$tempdir/usr/bin/sftpgo" "$install_dir"

ynh_safe_rm "$tempdir"

chmod +x "$install_dir/sftpgo"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="sftpgo.json" --destination="$install_dir/sftpgo.json"

chmod 400 "$install_dir/sftpgo.json"
chown "$app:$app" "$install_dir/sftpgo.json"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
