#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

tempdir="$(mktemp -d)"

ynh_setup_source --dest_dir="$install_dir"

# extract the binary from the deb file
dpkg-deb -R "$install_dir/sftpgo.deb" "$tempdir"

mv "$tempdir/usr/bin/sftpgo" "$install_dir"

ynh_safe_rm "$tempdir"

chmod +x "$install_dir/sftpgo"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template="some_config_file" --destination="$install_dir/some_config_file"

chmod 400 "$install_dir/some_config_file"
chown "$app:$app" "$install_dir/some_config_file"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="A short description of the app" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
